package javafragment

type JavaFragment interface {
	Accept(visitor JavaFragmentVisitor)
}

type JavaFragmentVisitor interface {
	VisitEndBodyFragment(fragment *EndBodyFragment)
	VisitEndBlockInParameterFragment(fragment *EndBlockInParameterFragment)
	VisitEndBlockFragment(fragment *EndBlockFragment)
	VisitEndBodyInParameterFragment(fragment *EndBodyInParameterFragment)
	VisitEndMovableJavaBlockFragment(fragment *EndMovableJavaBlockFragment)
	VisitEndSingleStatementBlockFragment(fragment *EndSingleStatementBlockFragment)
	VisitEndStatementsBlockFragment(fragment *EndStatementsBlockFragment)
	VisitImportsFragment(fragment *ImportsFragment)
	VisitLineNumberTokensFragment(fragment *LineNumberTokensFragment)
	VisitSpacerBetweenMembersFragment(fragment *SpacerBetweenMembersFragment)
	VisitSpacerFragment(fragment *SpacerFragment)
	VisitSpaceSpacerFragment(fragment *SpaceSpacerFragment)
	VisitStartBlockFragment(fragment *StartBlockFragment)
	VisitStartBodyFragment(fragment *StartBodyFragment)
	VisitStartMovableJavaBlockFragment(fragment *StartMovableJavaBlockFragment)
	VisitStartSingleStatementBlockFragment(fragment *StartSingleStatementBlockFragment)
	VisitStartStatementsBlockFragment(fragment *StartStatementsBlockFragment)
	VisitStartStatementsDoWhileBlockFragment(fragment *StartStatementsDoWhileBlockFragment)
	VisitStartStatementsInfiniteForBlockFragment(fragment *StartStatementsInfiniteForBlockFragment)
	VisitStartStatementsInfiniteWhileBlockFragment(fragment *StartStatementsInfiniteWhileBlockFragment)
	VisitStartStatementsTryBlockFragment(fragment *StartStatementsTryBlockFragment)
	VisitTokensFragment(fragment *TokensFragment)
}
